# Generated by Django 4.1.3 on 2025-06-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_profile_pic_customer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='street_address',
            new_name='billing_address',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='address_type',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
